# DO NOT COMMIT THE PASSWORDS
server:
  port: 8090
spring:
    main:
        web-environment: false
    thymeleaf:
        cache: false
    datasource:
        url: jdbc:postgresql://ec2-54-75-224-100.eu-west-1.compute.amazonaws.com:5432/d2f531u6mujsja?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
        username: naluedgflsuybx
        password: pass
        driver-class-name: org.postgresql.Driver
        dialect: org.hibernate.dialect.PostgreSQLDialect
        max-active: 5
        max-pool: 10
        max-idle: 0
    jpa:
        properties:
            hibernate:
                ddl-auto: update
                temp:
                    use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
    basic:
        enabled: false
#stormpath:
#    application:
#        href: https://api.stormpath.com/v1/applications/2QaziTvNf6JPRKpnE3FQ8a
#    web:
#        login:
#            nextUri: /home
#        logout:
#            nextUri: /public?action=logout


##  spring:
##    security:
##      enabled: false
##  client:
##      cacheManager:
##        enabled: true
##
